
    create table detalle_plan (
        cantidad integer not null,
        id bigint generated by default as identity,
        plan_semanal_id bigint not null,
        plato_id bigint not null,
        dia_semana varchar(15) not null,
        tipo_comida varchar(20) not null,
        primary key (id)
    );

    create table estadisticas_historicas (
        churn_rate numeric(5,2) not null,
        mrr numeric(10,2) not null,
        nuevos_negocios integer not null,
        fecha varchar(7) not null,
        id bigint generated by default as identity,
        primary key (id)
    );

    create table linea_pedido (
        cantidad integer not null,
        precio_unitario float(53) not null,
        id bigint generated by default as identity,
        pedido_id bigint not null,
        plato_id bigint not null,
        primary key (id)
    );

    create table negocio (
        fecha_registro timestamp(6) not null,
        id bigint generated by default as identity,
        ruc varchar(11) not null unique,
        telefono varchar(15),
        estado varchar(20) not null,
        plan varchar(50) not null,
        slug varchar(50) not null unique,
        ciudad varchar(100) not null,
        nombre_comercial varchar(150) not null,
        primary key (id)
    );

    create table pedido_ecommerce (
        fecha_entrega date,
        monto_total float(53) not null,
        negocio_id integer not null,
        fecha_creacion timestamp(6) not null,
        id bigint generated by default as identity,
        usuario_id bigint not null,
        estado varchar(30) not null,
        direccion_entrega varchar(255),
        primary key (id)
    );

    create table plan_semanal (
        fecha_inicio_semana date not null,
        monto_total float(53) not null,
        negocio_id integer not null,
        fecha_creacion timestamp(6) not null,
        id bigint generated by default as identity,
        usuario_id bigint not null,
        estado_pago varchar(20) not null,
        primary key (id)
    );

    create table plato (
        calorias float(53) not null,
        carbohidratos float(53) not null,
        disponible boolean not null,
        grasas float(53) not null,
        negocio_id integer not null,
        precio float(53) not null,
        proteinas float(53) not null,
        id bigint generated by default as identity,
        nombre varchar(120) not null,
        imagen_url varchar(1000),
        descripcion TEXT,
        etiquetas varchar(255),
        primary key (id)
    );

    create table suscripcion (
        id bigint generated by default as identity,
        negocio_id bigint not null,
        proximo_cobro timestamp(6),
        estado_pago varchar(50) not null,
        plan varchar(50) not null,
        stripe_customer_id varchar(255),
        stripe_subscription_id varchar(255),
        primary key (id)
    );

    create table usuario (
        negocio_id integer not null,
        req_carbohidratos_g float(53),
        req_grasas_g float(53),
        req_proteinas_g float(53),
        requerimiento_kcal float(53),
        id bigint generated by default as identity,
        estado varchar(20) not null,
        rol varchar(20) not null,
        objetivo_fitness varchar(50),
        apellidos varchar(100) not null,
        nombres varchar(100) not null,
        email varchar(150) not null unique,
        password_hash varchar(255) not null,
        primary key (id)
    );

    alter table if exists detalle_plan 
       add constraint FK5f4j28iohxpde4ke3g33uww7s 
       foreign key (plan_semanal_id) 
       references plan_semanal;

    alter table if exists detalle_plan 
       add constraint FKfygkxhrlfwdudjjvpvvb941of 
       foreign key (plato_id) 
       references plato;

    alter table if exists linea_pedido 
       add constraint FKmfq3e1kuxupokiktvrydit7vt 
       foreign key (pedido_id) 
       references pedido_ecommerce;

    alter table if exists plan_semanal 
       add constraint FKdn79k53vfcjruvmgfd7jud4i5 
       foreign key (usuario_id) 
       references usuario;
