/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantsIndexRouteImport } from './routes/tenants.index'
import { Route as TenantIndexRouteImport } from './routes/tenant.index'
import { Route as AthleteIndexRouteImport } from './routes/athlete.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TenantReportsRouteImport } from './routes/tenant.reports'
import { Route as TenantOrdersRouteImport } from './routes/tenant.orders'
import { Route as TenantMealsRouteImport } from './routes/tenant.meals'
import { Route as TenantDeliveryRouteImport } from './routes/tenant.delivery'
import { Route as TenantClientsRouteImport } from './routes/tenant.clients'
import { Route as AthleteSettingsRouteImport } from './routes/athlete.settings'
import { Route as AthleteProgressRouteImport } from './routes/athlete.progress'
import { Route as AthleteProfileRouteImport } from './routes/athlete.profile'
import { Route as AthletePlanRouteImport } from './routes/athlete.plan'
import { Route as AthleteOrdersRouteImport } from './routes/athlete.orders'
import { Route as AthleteGoalsRouteImport } from './routes/athlete.goals'
import { Route as AthleteCheckoutRouteImport } from './routes/athlete.checkout'
import { Route as AthleteCartRouteImport } from './routes/athlete.cart'
import { Route as AthleteAddMealRouteImport } from './routes/athlete.add-meal'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminBusinessesRouteImport } from './routes/admin.businesses'
import { Route as TenantsSlugIndexRouteImport } from './routes/tenants.$slug.index'
import { Route as TenantsSlugCatalogRouteImport } from './routes/tenants.$slug.catalog'
import { Route as TenantMealsNewRouteImport } from './routes/tenant.meals_.new'
import { Route as AthleteMealIdRouteImport } from './routes/athlete.meal.$id'
import { Route as TenantMealsIdEditRouteImport } from './routes/tenant.meals_.$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/tenant/',
  path: '/tenant/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteIndexRoute = AthleteIndexRouteImport.update({
  id: '/athlete/',
  path: '/athlete/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantReportsRoute = TenantReportsRouteImport.update({
  id: '/tenant/reports',
  path: '/tenant/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantOrdersRoute = TenantOrdersRouteImport.update({
  id: '/tenant/orders',
  path: '/tenant/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantMealsRoute = TenantMealsRouteImport.update({
  id: '/tenant/meals',
  path: '/tenant/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantDeliveryRoute = TenantDeliveryRouteImport.update({
  id: '/tenant/delivery',
  path: '/tenant/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantClientsRoute = TenantClientsRouteImport.update({
  id: '/tenant/clients',
  path: '/tenant/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteSettingsRoute = AthleteSettingsRouteImport.update({
  id: '/athlete/settings',
  path: '/athlete/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteProgressRoute = AthleteProgressRouteImport.update({
  id: '/athlete/progress',
  path: '/athlete/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteProfileRoute = AthleteProfileRouteImport.update({
  id: '/athlete/profile',
  path: '/athlete/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletePlanRoute = AthletePlanRouteImport.update({
  id: '/athlete/plan',
  path: '/athlete/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteOrdersRoute = AthleteOrdersRouteImport.update({
  id: '/athlete/orders',
  path: '/athlete/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteGoalsRoute = AthleteGoalsRouteImport.update({
  id: '/athlete/goals',
  path: '/athlete/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteCheckoutRoute = AthleteCheckoutRouteImport.update({
  id: '/athlete/checkout',
  path: '/athlete/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteCartRoute = AthleteCartRouteImport.update({
  id: '/athlete/cart',
  path: '/athlete/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteAddMealRoute = AthleteAddMealRouteImport.update({
  id: '/athlete/add-meal',
  path: '/athlete/add-meal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({
  id: '/admin/businesses',
  path: '/admin/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsSlugIndexRoute = TenantsSlugIndexRouteImport.update({
  id: '/tenants/$slug/',
  path: '/tenants/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsSlugCatalogRoute = TenantsSlugCatalogRouteImport.update({
  id: '/tenants/$slug/catalog',
  path: '/tenants/$slug/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantMealsNewRoute = TenantMealsNewRouteImport.update({
  id: '/tenant/meals_/new',
  path: '/tenant/meals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteMealIdRoute = AthleteMealIdRouteImport.update({
  id: '/athlete/meal/$id',
  path: '/athlete/meal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantMealsIdEditRoute = TenantMealsIdEditRouteImport.update({
  id: '/tenant/meals_/$id/edit',
  path: '/tenant/meals/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/athlete/add-meal': typeof AthleteAddMealRoute
  '/athlete/cart': typeof AthleteCartRoute
  '/athlete/checkout': typeof AthleteCheckoutRoute
  '/athlete/goals': typeof AthleteGoalsRoute
  '/athlete/orders': typeof AthleteOrdersRoute
  '/athlete/plan': typeof AthletePlanRoute
  '/athlete/profile': typeof AthleteProfileRoute
  '/athlete/progress': typeof AthleteProgressRoute
  '/athlete/settings': typeof AthleteSettingsRoute
  '/tenant/clients': typeof TenantClientsRoute
  '/tenant/delivery': typeof TenantDeliveryRoute
  '/tenant/meals': typeof TenantMealsRoute
  '/tenant/orders': typeof TenantOrdersRoute
  '/tenant/reports': typeof TenantReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/athlete/': typeof AthleteIndexRoute
  '/tenant/': typeof TenantIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/athlete/meal/$id': typeof AthleteMealIdRoute
  '/tenant/meals/new': typeof TenantMealsNewRoute
  '/tenants/$slug/catalog': typeof TenantsSlugCatalogRoute
  '/tenants/$slug/': typeof TenantsSlugIndexRoute
  '/tenant/meals/$id/edit': typeof TenantMealsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/athlete/add-meal': typeof AthleteAddMealRoute
  '/athlete/cart': typeof AthleteCartRoute
  '/athlete/checkout': typeof AthleteCheckoutRoute
  '/athlete/goals': typeof AthleteGoalsRoute
  '/athlete/orders': typeof AthleteOrdersRoute
  '/athlete/plan': typeof AthletePlanRoute
  '/athlete/profile': typeof AthleteProfileRoute
  '/athlete/progress': typeof AthleteProgressRoute
  '/athlete/settings': typeof AthleteSettingsRoute
  '/tenant/clients': typeof TenantClientsRoute
  '/tenant/delivery': typeof TenantDeliveryRoute
  '/tenant/meals': typeof TenantMealsRoute
  '/tenant/orders': typeof TenantOrdersRoute
  '/tenant/reports': typeof TenantReportsRoute
  '/admin': typeof AdminIndexRoute
  '/athlete': typeof AthleteIndexRoute
  '/tenant': typeof TenantIndexRoute
  '/tenants': typeof TenantsIndexRoute
  '/athlete/meal/$id': typeof AthleteMealIdRoute
  '/tenant/meals/new': typeof TenantMealsNewRoute
  '/tenants/$slug/catalog': typeof TenantsSlugCatalogRoute
  '/tenants/$slug': typeof TenantsSlugIndexRoute
  '/tenant/meals/$id/edit': typeof TenantMealsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/athlete/add-meal': typeof AthleteAddMealRoute
  '/athlete/cart': typeof AthleteCartRoute
  '/athlete/checkout': typeof AthleteCheckoutRoute
  '/athlete/goals': typeof AthleteGoalsRoute
  '/athlete/orders': typeof AthleteOrdersRoute
  '/athlete/plan': typeof AthletePlanRoute
  '/athlete/profile': typeof AthleteProfileRoute
  '/athlete/progress': typeof AthleteProgressRoute
  '/athlete/settings': typeof AthleteSettingsRoute
  '/tenant/clients': typeof TenantClientsRoute
  '/tenant/delivery': typeof TenantDeliveryRoute
  '/tenant/meals': typeof TenantMealsRoute
  '/tenant/orders': typeof TenantOrdersRoute
  '/tenant/reports': typeof TenantReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/athlete/': typeof AthleteIndexRoute
  '/tenant/': typeof TenantIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/athlete/meal/$id': typeof AthleteMealIdRoute
  '/tenant/meals_/new': typeof TenantMealsNewRoute
  '/tenants/$slug/catalog': typeof TenantsSlugCatalogRoute
  '/tenants/$slug/': typeof TenantsSlugIndexRoute
  '/tenant/meals_/$id/edit': typeof TenantMealsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot'
    | '/login'
    | '/register'
    | '/admin/businesses'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/athlete/add-meal'
    | '/athlete/cart'
    | '/athlete/checkout'
    | '/athlete/goals'
    | '/athlete/orders'
    | '/athlete/plan'
    | '/athlete/profile'
    | '/athlete/progress'
    | '/athlete/settings'
    | '/tenant/clients'
    | '/tenant/delivery'
    | '/tenant/meals'
    | '/tenant/orders'
    | '/tenant/reports'
    | '/admin/'
    | '/athlete/'
    | '/tenant/'
    | '/tenants/'
    | '/athlete/meal/$id'
    | '/tenant/meals/new'
    | '/tenants/$slug/catalog'
    | '/tenants/$slug/'
    | '/tenant/meals/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot'
    | '/login'
    | '/register'
    | '/admin/businesses'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/athlete/add-meal'
    | '/athlete/cart'
    | '/athlete/checkout'
    | '/athlete/goals'
    | '/athlete/orders'
    | '/athlete/plan'
    | '/athlete/profile'
    | '/athlete/progress'
    | '/athlete/settings'
    | '/tenant/clients'
    | '/tenant/delivery'
    | '/tenant/meals'
    | '/tenant/orders'
    | '/tenant/reports'
    | '/admin'
    | '/athlete'
    | '/tenant'
    | '/tenants'
    | '/athlete/meal/$id'
    | '/tenant/meals/new'
    | '/tenants/$slug/catalog'
    | '/tenants/$slug'
    | '/tenant/meals/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/forgot'
    | '/login'
    | '/register'
    | '/admin/businesses'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/athlete/add-meal'
    | '/athlete/cart'
    | '/athlete/checkout'
    | '/athlete/goals'
    | '/athlete/orders'
    | '/athlete/plan'
    | '/athlete/profile'
    | '/athlete/progress'
    | '/athlete/settings'
    | '/tenant/clients'
    | '/tenant/delivery'
    | '/tenant/meals'
    | '/tenant/orders'
    | '/tenant/reports'
    | '/admin/'
    | '/athlete/'
    | '/tenant/'
    | '/tenants/'
    | '/athlete/meal/$id'
    | '/tenant/meals_/new'
    | '/tenants/$slug/catalog'
    | '/tenants/$slug/'
    | '/tenant/meals_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminBusinessesRoute: typeof AdminBusinessesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AthleteAddMealRoute: typeof AthleteAddMealRoute
  AthleteCartRoute: typeof AthleteCartRoute
  AthleteCheckoutRoute: typeof AthleteCheckoutRoute
  AthleteGoalsRoute: typeof AthleteGoalsRoute
  AthleteOrdersRoute: typeof AthleteOrdersRoute
  AthletePlanRoute: typeof AthletePlanRoute
  AthleteProfileRoute: typeof AthleteProfileRoute
  AthleteProgressRoute: typeof AthleteProgressRoute
  AthleteSettingsRoute: typeof AthleteSettingsRoute
  TenantClientsRoute: typeof TenantClientsRoute
  TenantDeliveryRoute: typeof TenantDeliveryRoute
  TenantMealsRoute: typeof TenantMealsRoute
  TenantOrdersRoute: typeof TenantOrdersRoute
  TenantReportsRoute: typeof TenantReportsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AthleteIndexRoute: typeof AthleteIndexRoute
  TenantIndexRoute: typeof TenantIndexRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
  AthleteMealIdRoute: typeof AthleteMealIdRoute
  TenantMealsNewRoute: typeof TenantMealsNewRoute
  TenantsSlugCatalogRoute: typeof TenantsSlugCatalogRoute
  TenantsSlugIndexRoute: typeof TenantsSlugIndexRoute
  TenantMealsIdEditRoute: typeof TenantMealsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/tenant'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/': {
      id: '/athlete/'
      path: '/athlete'
      fullPath: '/athlete/'
      preLoaderRoute: typeof AthleteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/reports': {
      id: '/tenant/reports'
      path: '/tenant/reports'
      fullPath: '/tenant/reports'
      preLoaderRoute: typeof TenantReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/orders': {
      id: '/tenant/orders'
      path: '/tenant/orders'
      fullPath: '/tenant/orders'
      preLoaderRoute: typeof TenantOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/meals': {
      id: '/tenant/meals'
      path: '/tenant/meals'
      fullPath: '/tenant/meals'
      preLoaderRoute: typeof TenantMealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/delivery': {
      id: '/tenant/delivery'
      path: '/tenant/delivery'
      fullPath: '/tenant/delivery'
      preLoaderRoute: typeof TenantDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/clients': {
      id: '/tenant/clients'
      path: '/tenant/clients'
      fullPath: '/tenant/clients'
      preLoaderRoute: typeof TenantClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/settings': {
      id: '/athlete/settings'
      path: '/athlete/settings'
      fullPath: '/athlete/settings'
      preLoaderRoute: typeof AthleteSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/progress': {
      id: '/athlete/progress'
      path: '/athlete/progress'
      fullPath: '/athlete/progress'
      preLoaderRoute: typeof AthleteProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/profile': {
      id: '/athlete/profile'
      path: '/athlete/profile'
      fullPath: '/athlete/profile'
      preLoaderRoute: typeof AthleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/plan': {
      id: '/athlete/plan'
      path: '/athlete/plan'
      fullPath: '/athlete/plan'
      preLoaderRoute: typeof AthletePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/orders': {
      id: '/athlete/orders'
      path: '/athlete/orders'
      fullPath: '/athlete/orders'
      preLoaderRoute: typeof AthleteOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/goals': {
      id: '/athlete/goals'
      path: '/athlete/goals'
      fullPath: '/athlete/goals'
      preLoaderRoute: typeof AthleteGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/checkout': {
      id: '/athlete/checkout'
      path: '/athlete/checkout'
      fullPath: '/athlete/checkout'
      preLoaderRoute: typeof AthleteCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/cart': {
      id: '/athlete/cart'
      path: '/athlete/cart'
      fullPath: '/athlete/cart'
      preLoaderRoute: typeof AthleteCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/add-meal': {
      id: '/athlete/add-meal'
      path: '/athlete/add-meal'
      fullPath: '/athlete/add-meal'
      preLoaderRoute: typeof AthleteAddMealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/businesses': {
      id: '/admin/businesses'
      path: '/admin/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AdminBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/$slug/': {
      id: '/tenants/$slug/'
      path: '/tenants/$slug'
      fullPath: '/tenants/$slug/'
      preLoaderRoute: typeof TenantsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/$slug/catalog': {
      id: '/tenants/$slug/catalog'
      path: '/tenants/$slug/catalog'
      fullPath: '/tenants/$slug/catalog'
      preLoaderRoute: typeof TenantsSlugCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/meals_/new': {
      id: '/tenant/meals_/new'
      path: '/tenant/meals/new'
      fullPath: '/tenant/meals/new'
      preLoaderRoute: typeof TenantMealsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/meal/$id': {
      id: '/athlete/meal/$id'
      path: '/athlete/meal/$id'
      fullPath: '/athlete/meal/$id'
      preLoaderRoute: typeof AthleteMealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/meals_/$id/edit': {
      id: '/tenant/meals_/$id/edit'
      path: '/tenant/meals/$id/edit'
      fullPath: '/tenant/meals/$id/edit'
      preLoaderRoute: typeof TenantMealsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminBusinessesRoute: AdminBusinessesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AthleteAddMealRoute: AthleteAddMealRoute,
  AthleteCartRoute: AthleteCartRoute,
  AthleteCheckoutRoute: AthleteCheckoutRoute,
  AthleteGoalsRoute: AthleteGoalsRoute,
  AthleteOrdersRoute: AthleteOrdersRoute,
  AthletePlanRoute: AthletePlanRoute,
  AthleteProfileRoute: AthleteProfileRoute,
  AthleteProgressRoute: AthleteProgressRoute,
  AthleteSettingsRoute: AthleteSettingsRoute,
  TenantClientsRoute: TenantClientsRoute,
  TenantDeliveryRoute: TenantDeliveryRoute,
  TenantMealsRoute: TenantMealsRoute,
  TenantOrdersRoute: TenantOrdersRoute,
  TenantReportsRoute: TenantReportsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AthleteIndexRoute: AthleteIndexRoute,
  TenantIndexRoute: TenantIndexRoute,
  TenantsIndexRoute: TenantsIndexRoute,
  AthleteMealIdRoute: AthleteMealIdRoute,
  TenantMealsNewRoute: TenantMealsNewRoute,
  TenantsSlugCatalogRoute: TenantsSlugCatalogRoute,
  TenantsSlugIndexRoute: TenantsSlugIndexRoute,
  TenantMealsIdEditRoute: TenantMealsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
